Repository AY2021S1-CS2113T-T09-2/tp, pull requests merged in 2020-10, with the labels that each got.

#12 Added base Task and Module classes
  src/main/java/seedu/duke/data/Module.java
  src/main/java/seedu/duke/data/Task.java
  src/main/java/seedu/duke/directory/Module.java
  src/main/java/seedu/duke/directory/Task.java
Labels: priority.High

#36 Added NUSMods module HashMap and fixed formatting
  src/main/java/seedu/duke/data/ModuleManager.java
  src/main/java/seedu/duke/data/TaskManager.java
Labels: type.Documentation

#35 Fix DeleteCommand bug and checkstyle violations
  build.gradle
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/PromptType.java
  src/main/java/seedu/duke/command/add/AddCommand.java
  src/main/java/seedu/duke/command/delete/DeleteCommand.java
  src/main/java/seedu/duke/command/done/DoneCommand.java
  src/main/java/seedu/duke/command/list/ListCommand.java
  src/main/java/seedu/duke/data/ModuleManager.java
  src/main/java/seedu/duke/data/Task.java
  src/main/java/seedu/duke/data/TaskManager.java
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/TextUi.java
  src/main/java/seedu/duke/util/ExceptionMessage.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Bug

#52 Fixed Parser Bugs
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/TextUi.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#53 Fix bugs of the main class workflow
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/data/Module.java
  src/main/java/seedu/duke/data/Task.java
  src/main/java/seedu/duke/parser/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug

#56 Add save to main
  src/main/java/seedu/duke/Duke.java
Labels: priority.High

#55 Updated parser and added JUnit test
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/util/ExceptionMessage.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Bug

#54 Add JUnit tests for Add, Delete
  src/test/java/seedu/duke/command/add/AddCommandTest.java
  src/test/java/seedu/duke/command/delete/DeleteCommandTest.java
Labels: type.Task

#62 Update help message
  src/main/java/seedu/duke/util/Message.java
Labels: type.Bug

#44 Add EditTaskCommand class and Update EditModuleCommand class
  build.gradle
  data/mod_data.json
  data/task_data.json
  mod_data.json
  src/main/java/seedu/duke/command/edit/EditCommand.java
  src/main/java/seedu/duke/command/edit/EditModuleCommand.java
  src/main/java/seedu/duke/command/edit/EditTaskCommand.java
  src/main/java/seedu/duke/data/Task.java
  src/main/java/seedu/duke/data/TaskManager.java
  src/main/java/seedu/duke/data/storage/Decoder.java
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
  src/main/java/seedu/duke/exception/TaskNotFoundException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/util/Message.java
  src/test/java/seedu/duke/command/edit/EditModuleCommandTest.java
  src/test/java/seedu/duke/command/edit/EditTaskCommandTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
  task_data.json
Labels: type.Task

#63 Fix parser bug
  src/main/java/seedu/duke/parser/Parser.java
Labels: type.Bug

#67 Fix parser
  data/mod_data.json
  data/task_data.json
  mod_data.json
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  task_data.json
Labels: type.Bug

#72 Added DukeLogger class and added its setup in main Duke class
  .gitignore
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/DukeLogger.java
  src/main/java/seedu/duke/data/TaskManager.java
  src/main/java/seedu/duke/data/storage/Decoder.java
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
  src/test/java/seedu/duke/data/TaskTest.java
Labels: type.Story

#78 Update parser, split into individual Commands
  src/main/java/seedu/duke/parser/AddCommandParser.java
  src/main/java/seedu/duke/parser/DeleteCommandParser.java
  src/main/java/seedu/duke/parser/DoneCommandParser.java
  src/main/java/seedu/duke/parser/EditCommandParser.java
  src/main/java/seedu/duke/parser/ListCommandParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Enhancement

#77 Add Undo command
  build.gradle
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Executor.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/add/AddCommand.java
  src/main/java/seedu/duke/command/delete/DeleteCommand.java
  src/main/java/seedu/duke/command/edit/EditTaskCommand.java
  src/main/java/seedu/duke/command/list/ListCommand.java
  src/main/java/seedu/duke/command/misc/UndoCommand.java
  src/main/java/seedu/duke/data/ModuleManager.java
  src/main/java/seedu/duke/data/State.java
  src/main/java/seedu/duke/data/StateManager.java
  src/main/java/seedu/duke/data/Task.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/util/Message.java
  src/test/java/seedu/duke/command/misc/UndoCommandTest.java
Labels: type.Story, type.Task

#80 Added Lesson classes and basic 'timetable' functionality
  src/main/java/seedu/duke/data/Lesson.java
  src/main/java/seedu/duke/data/LessonFilter.java
  src/main/java/seedu/duke/data/LessonManager.java
  src/main/java/seedu/duke/data/LessonType.java
  src/main/java/seedu/duke/exception/LessonInvalidTimeException.java
  src/main/java/seedu/duke/exception/LessonNotFoundException.java
  src/test/java/seedu/duke/data/LessonTest.java
  src/test/java/seedu/duke/data/ModuleTest.java
Labels: type.Task

#82 Split Add and Delete commands
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/add/AddCommand.java
  src/main/java/seedu/duke/command/add/AddModuleCommand.java
  src/main/java/seedu/duke/command/add/AddTaskCommand.java
  src/main/java/seedu/duke/command/delete/DeleteCommand.java
  src/main/java/seedu/duke/command/delete/DeleteModuleCommand.java
  src/main/java/seedu/duke/command/delete/DeleteTaskCommand.java
  src/main/java/seedu/duke/parser/AddCommandParser.java
  src/main/java/seedu/duke/parser/DeleteCommandParser.java
  src/test/java/seedu/duke/command/add/AddCommandTest.java
  src/test/java/seedu/duke/command/delete/DeleteCommandTest.java
Labels: type.Enhancement

#90 Fixed delcommand format and intparser bug
  src/main/java/seedu/duke/parser/DeleteCommandParser.java
Labels: severity.Medium, type.Bug

#97 Add manual testing to add task/module in DeveloperGuide
  docs/DeveloperGuide.md
Labels: type.Documentation

#100 UML class diagrams and updated Dev Guide
  docs/DeveloperGuide.md
  docs/diagrams/CommandClassDiagram.png
  docs/diagrams/DataClassDiagram.png
  docs/diagrams/MainClassDiagram.png
  docs/diagrams/ParserClassDiagram.png
  docs/diagrams/UML/CommandClassDiagram.puml
  docs/diagrams/UML/DataClassDiagram.puml
  docs/diagrams/UML/MainClassDiagram.puml
  docs/diagrams/UML/ParserClassDiagram.puml
Labels: type.Documentation

#101 Add timetable
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/timetable/TimeTableAddCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableDeleteCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableFilterCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableViewCommand.java
  src/main/java/seedu/duke/data/Lesson.java
  src/main/java/seedu/duke/data/LessonManager.java
  src/main/java/seedu/duke/data/LessonType.java
  src/main/java/seedu/duke/data/ModuleManager.java
  src/main/java/seedu/duke/data/TimeTableManager.java
  src/main/java/seedu/duke/exception/RepeatFrequencyInvalidException.java
  src/main/java/seedu/duke/exception/TimeTableInitialiseException.java
  src/main/java/seedu/duke/parser/LessonParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/TimeTableCommandParser.java
  src/main/java/seedu/duke/ui/TextUi.java
  src/main/java/seedu/duke/util/ExceptionMessage.java
  src/main/java/seedu/duke/util/Message.java
  src/test/java/seedu/duke/data/LessonTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story

#103 Timetable save/load functionality and timetable unit test
  src/main/java/seedu/duke/command/timetable/TimeTableAddCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableDeleteCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableViewCommand.java
  src/main/java/seedu/duke/common/Constant.java
  src/main/java/seedu/duke/data/Lesson.java
  src/main/java/seedu/duke/data/LessonManager.java
  src/main/java/seedu/duke/data/ModuleManager.java
  src/main/java/seedu/duke/data/TimeTable.java
  src/main/java/seedu/duke/data/TimeTableManager.java
  src/main/java/seedu/duke/data/storage/Decoder.java
  src/main/java/seedu/duke/data/storage/Encoder.java
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
  src/main/java/seedu/duke/parser/TimeTableCommandParser.java
  src/main/java/seedu/duke/util/ExceptionMessage.java
  src/main/java/seedu/duke/util/FileName.java
  src/test/java/seedu/duke/data/LessonTest.java
  src/test/java/seedu/duke/data/TimeTableTest.java
Labels: priority.High

#104 Enabled Assertions
  build.gradle
Labels: priority.High

#85 Added Grade and Cap Command
  src/main/java/seedu/duke/command/cap/CapCommand.java
  src/main/java/seedu/duke/command/grade/GradeCommand.java
  src/main/java/seedu/duke/data/Module.java
  src/main/java/seedu/duke/data/ModuleManager.java
  src/main/java/seedu/duke/exception/InvalidGradeException.java
  src/main/java/seedu/duke/parser/AddCommandParser.java
  src/main/java/seedu/duke/parser/CapCommandParser.java
  src/main/java/seedu/duke/parser/DeleteCommandParser.java
  src/main/java/seedu/duke/parser/DoneCommandParser.java
  src/main/java/seedu/duke/parser/EditCommandParser.java
  src/main/java/seedu/duke/parser/GradeCommandParser.java
  src/main/java/seedu/duke/parser/ListCommandParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/TimeTableCommandParser.java
  src/main/java/seedu/duke/util/ExceptionMessage.java
  src/main/java/seedu/duke/util/Message.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Story

#109 Fix formatting and JavaDoc for AddDelete
  src/main/java/seedu/duke/command/add/AddModuleCommand.java
  src/main/java/seedu/duke/command/add/AddTaskCommand.java
  src/main/java/seedu/duke/command/delete/DeleteModuleCommand.java
  src/main/java/seedu/duke/command/delete/DeleteTaskCommand.java
Labels: type.Documentation

#105 Made diagrams more compact
  docs/diagrams/CommandClassDiagram.png
  docs/diagrams/ParserClassDiagram.png
  docs/diagrams/UML/CommandClassDiagram.puml
  docs/diagrams/UML/ParserClassDiagram.puml
Labels: type.Documentation

#92 Verification against NUSMods when user adds module
  src/main/java/seedu/duke/command/add/AddModuleCommand.java
  src/main/java/seedu/duke/data/ModuleManager.java
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
  src/test/java/seedu/duke/command/add/AddCommandTest.java
  src/test/java/seedu/duke/command/misc/UndoCommandTest.java
  src/test/java/seedu/duke/data/ModuleTest.java
  src/test/java/seedu/duke/data/TimeTableTest.java
Labels: type.Task

#106 Update UserGuide
  docs/UserGuide.md
Labels: type.Documentation

#113 Fixed parser matchermatches bug
  src/main/java/seedu/duke/exception/InvalidMatchException.java
  src/main/java/seedu/duke/parser/AddCommandParser.java
  src/main/java/seedu/duke/parser/CapCommandParser.java
  src/main/java/seedu/duke/parser/DeleteCommandParser.java
  src/main/java/seedu/duke/parser/DoneCommandParser.java
  src/main/java/seedu/duke/parser/EditCommandParser.java
  src/main/java/seedu/duke/parser/GradeCommandParser.java
  src/main/java/seedu/duke/parser/ListCommandParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/TimeTableCommandParser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: priority.High, type.Bug

#116 Update feature description for UG
  docs/UserGuide.md
Labels: type.Documentation

#114 Add JUnit tests for TimeTableCommand and TimeTableCommandParser
  src/main/java/seedu/duke/command/timetable/TimeTableAddCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableDeleteCommand.java
  src/main/java/seedu/duke/data/TimeTableManager.java
  src/main/java/seedu/duke/parser/LessonParser.java
  src/main/java/seedu/duke/parser/TimeTableCommandParser.java
  src/main/java/seedu/duke/util/ExceptionMessage.java
  src/test/java/seedu/duke/command/timetable/TimeTableCommandTest.java
  src/test/java/seedu/duke/parser/TimeTableCommandParserTest.java
Labels: type.Documentation

#110 Add sequence diagram for AddCommand
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSequenceDiagram.png
  docs/diagrams/UML/AddCommandSequenceDiagram.puml
Labels: type.Documentation

#119 Added Javadocs and Parser tests, Grade and Cap Tests
  CapCommandSequenceDiagram.png
  CapCommandSequenceDiagram.puml
  GradeCommandSequenceDiagram.png
  GradeCommandSequenceDiagram.puml
  src/main/java/seedu/duke/parser/AddCommandParser.java
  src/main/java/seedu/duke/parser/CapCommandParser.java
  src/main/java/seedu/duke/parser/DeleteCommandParser.java
  src/main/java/seedu/duke/parser/DoneCommandParser.java
  src/main/java/seedu/duke/parser/EditCommandParser.java
  src/main/java/seedu/duke/parser/GradeCommandParser.java
  src/main/java/seedu/duke/parser/HelpCommandParser.java
  src/main/java/seedu/duke/parser/ListCommandParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/command/cap/CapCommandTest.java
  src/test/java/seedu/duke/command/grade/GradeCommandTest.java
  src/test/java/seedu/duke/parser/AddCommandParserTest.java
  src/test/java/seedu/duke/parser/CapCommandParserTest.java
  src/test/java/seedu/duke/parser/DeleteCommandParserTest.java
  src/test/java/seedu/duke/parser/DoneCommandParserTest.java
  src/test/java/seedu/duke/parser/EditCommandParserTest.java
  src/test/java/seedu/duke/parser/GradeCommandParserTest.java
  src/test/java/seedu/duke/parser/HelpCommandParserTest.java
  src/test/java/seedu/duke/parser/ListCommandParserTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Test

#121 Added Main Sequence Diagram
  docs/UserGuide.md
  docs/diagrams/MainSequenceDiagram.png
  docs/diagrams/UML/MainSequenceDiagram.puml
Labels: type.Documentation

#112 Added Cap and Grade Seq diagrams
  docs/DeveloperGuide.md
  docs/diagrams/CapCommandSequenceDiagram.png
  docs/diagrams/GradeCommandSequenceDiagram.png
  docs/diagrams/UML/CapCommandSequenceDiagram.puml
  docs/diagrams/UML/GradeCommandSequenceDiagram.puml
Labels: type.Documentation

#122 Add TimeTable feature and amended diagrams for the DG
  docs/DeveloperGuide.md
  docs/diagrams/CommandClassDiagram.png
  docs/diagrams/DataClassDiagram.png
  docs/diagrams/TimeTableClassDiagram.png
  docs/diagrams/UML/AddCommandSequenceDiagram.puml
  docs/diagrams/UML/CommandClassDiagram.puml
  docs/diagrams/UML/DataClassDiagram.puml
  docs/diagrams/UML/TimeTableClassDiagram.puml
  src/main/java/seedu/duke/command/timetable/TimeTableDeleteCommand.java
  src/main/java/seedu/duke/data/TimeTable.java
  src/main/java/seedu/duke/data/TimeTableManager.java
  src/test/java/seedu/duke/data/TimeTableTest.java
Labels: type.Documentation

#118 Add more JUnit tests to timetable
  src/test/java/seedu/duke/command/delete/DeleteCommandTest.java
  src/test/java/seedu/duke/data/TimeTableTest.java
  src/test/java/seedu/duke/parser/TimeTableCommandParserTest.java
Labels: type.Test

#124 Fixing copy issue
  CapCommandSequenceDiagram.png
  CapCommandSequenceDiagram.puml
  GradeCommandSequenceDiagram.png
  GradeCommandSequenceDiagram.puml
Labels: priority.High

#125 Big formatting changes, minor code cleanup, and DateTime parsing bug fix
  .github/workflows/gradle.yml
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/DukeLogger.java
  src/main/java/seedu/duke/command/IncorrectCommand.java
  src/main/java/seedu/duke/command/add/AddModuleCommand.java
  src/main/java/seedu/duke/command/add/AddTaskCommand.java
  src/main/java/seedu/duke/command/cap/CapCommand.java
  src/main/java/seedu/duke/command/delete/DeleteModuleCommand.java
  src/main/java/seedu/duke/command/delete/DeleteTaskCommand.java
  src/main/java/seedu/duke/command/done/DoneCommand.java
  src/main/java/seedu/duke/command/edit/EditModuleCommand.java
  src/main/java/seedu/duke/command/edit/EditTaskCommand.java
  src/main/java/seedu/duke/command/filter/FilterCommand.java
  src/main/java/seedu/duke/command/grade/GradeCommand.java
  src/main/java/seedu/duke/command/help/HelpCommand.java
  src/main/java/seedu/duke/command/list/ListCommand.java
  src/main/java/seedu/duke/command/summary/SummaryCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableAddCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableDeleteCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableViewCommand.java
  src/main/java/seedu/duke/data/LessonManager.java
  src/main/java/seedu/duke/data/ModuleManager.java
  src/main/java/seedu/duke/data/State.java
  src/main/java/seedu/duke/data/Task.java
  src/main/java/seedu/duke/data/TimeTableManager.java
  src/main/java/seedu/duke/data/storage/Decoder.java
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
  src/main/java/seedu/duke/parser/AddCommandParser.java
  src/main/java/seedu/duke/parser/DeleteCommandParser.java
  src/main/java/seedu/duke/parser/EditCommandParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/TimeTableCommandParser.java
  src/main/java/seedu/duke/ui/TextUi.java
  src/main/java/seedu/duke/util/ExceptionMessage.java
  src/main/java/seedu/duke/util/Message.java
  src/test/java/seedu/duke/command/edit/EditTaskCommandTest.java
  src/test/java/seedu/duke/command/help/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: type.Bug, type.Enhancement

#128 Fix minor DG issues
  docs/DeveloperGuide.md
Labels: type.Documentation

#130 Amend visibility of parse methods in TimeTableCommandParser and fix associated JUnit tests
  src/main/java/seedu/duke/parser/TimeTableCommandParser.java
  src/test/java/seedu/duke/command/timetable/TimeTableCommandTest.java
  src/test/java/seedu/duke/parser/TimeTableCommandParserTest.java
Labels: type.Test

#133 Add ListCommand sequence diagram and implementation in dg
  docs/DeveloperGuide.md
  docs/diagrams/ListCommandSequenceDiagram.png
  docs/diagrams/UML/ListCommandSequenceDiagram.puml
Labels: type.Documentation

#134 Added timetable filter command
  src/main/java/seedu/duke/command/timetable/TimeTableCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableFilterCommand.java
  src/main/java/seedu/duke/data/LessonManager.java
  src/main/java/seedu/duke/data/TimeTableManager.java
  src/main/java/seedu/duke/parser/LessonParser.java
  src/main/java/seedu/duke/parser/TimeTableCommandParser.java
  src/test/java/seedu/duke/data/LessonTest.java
Labels: type.Task

#139 Update user stories and link to v2.0 for DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#141 Fixed images in DG and tidied README
  docs/DeveloperGuide.md
  docs/README.md
Labels: type.Documentation

#142 Fixed DevGuide images
  docs/DeveloperGuide.md
Labels: type.Bug, type.Documentation

#143 Polishing DG and adding Main Sequence Diagram
  docs/DeveloperGuide.md
  docs/diagrams/MainSequenceDiagram.png
Labels: type.Documentation

#150 Fixed timetable not saving when there are no lessons
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
Labels: severity.Medium, type.Bug

#152 Fixed undo not stepping for done command
  src/main/java/seedu/duke/command/done/DoneCommand.java
Labels: severity.High, type.Bug

#227 Fixed undo undoing multiple commands
  src/main/java/seedu/duke/command/add/AddModuleCommand.java
  src/main/java/seedu/duke/command/add/AddTaskCommand.java
  src/main/java/seedu/duke/command/cap/CapCommand.java
  src/main/java/seedu/duke/command/done/DoneCommand.java
  src/main/java/seedu/duke/command/edit/EditModuleCommand.java
  src/main/java/seedu/duke/command/edit/EditTaskCommand.java
  src/main/java/seedu/duke/command/filter/FilterCommand.java
  src/main/java/seedu/duke/command/grade/GradeCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableAddCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableDeleteCommand.java
Labels: type.Bug

#226 Granular loading and fixed task status loading
  src/main/java/seedu/duke/data/StateManager.java
  src/main/java/seedu/duke/data/Task.java
  src/main/java/seedu/duke/data/TaskManager.java
  src/main/java/seedu/duke/data/storage/Decoder.java
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
  src/main/java/seedu/duke/ui/TextUi.java
  src/main/java/seedu/duke/util/Message.java
  src/test/java/seedu/duke/data/TaskTest.java
Labels: type.Bug
