Repository AY2021S1-CS2113T-T09-2/tp, pull requests merged in 2020-11, with the labels that each got.

#228 Major fix of ModuleManager functions and exceptions
  src/main/java/seedu/duke/command/add/AddModuleCommand.java
  src/main/java/seedu/duke/command/delete/DeleteModuleCommand.java
  src/main/java/seedu/duke/command/edit/EditModuleCommand.java
  src/main/java/seedu/duke/command/grade/GradeCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableAddCommand.java
  src/main/java/seedu/duke/data/ModuleManager.java
  src/main/java/seedu/duke/data/TimeTableManager.java
  src/main/java/seedu/duke/data/storage/Encoder.java
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
  src/main/java/seedu/duke/exception/DuplicateModuleException.java
  src/main/java/seedu/duke/exception/ModuleNotFoundException.java
  src/main/java/seedu/duke/parser/LessonParser.java
  src/main/java/seedu/duke/parser/TimeTableCommandParser.java
  src/test/java/seedu/duke/command/edit/EditModuleCommandTest.java
  src/test/java/seedu/duke/command/timetable/TimeTableCommandTest.java
  src/test/java/seedu/duke/data/ModuleTest.java
  src/test/java/seedu/duke/data/TimeTableTest.java
  src/test/java/seedu/duke/parser/TimeTableCommandParserTest.java
Labels: priority.High, type.Enhancement

#229 Made adding tasks/mods/lessons show result
  src/main/java/seedu/duke/command/add/AddModuleCommand.java
  src/main/java/seedu/duke/command/add/AddTaskCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableAddCommand.java
  src/main/java/seedu/duke/data/Task.java
  src/main/java/seedu/duke/util/Message.java
Labels: type.Enhancement

#232 Made addLesson check overlap before adding; relevant tests
  src/main/java/seedu/duke/command/timetable/TimeTableAddCommand.java
  src/main/java/seedu/duke/data/TimeTableManager.java
  src/main/java/seedu/duke/exception/LessonOverlapException.java
  src/main/java/seedu/duke/util/ExceptionMessage.java
  src/test/java/seedu/duke/command/timetable/TimeTableCommandTest.java
  src/test/java/seedu/duke/data/TimeTableTest.java
Labels: type.Bug

#234 Added edit deadline functionality
  src/main/java/seedu/duke/command/add/AddTaskCommand.java
  src/main/java/seedu/duke/command/edit/EditCommand.java
  src/main/java/seedu/duke/command/edit/EditTaskCommand.java
  src/main/java/seedu/duke/data/TaskManager.java
  src/main/java/seedu/duke/parser/EditCommandParser.java
  src/test/java/seedu/duke/command/edit/EditTaskCommandTest.java
  src/test/java/seedu/duke/data/TaskTest.java
Labels: type.Enhancement

#237 Added handler for Ctrl C - no saving
  src/main/java/seedu/duke/Duke.java
Labels: type.Enhancement

#235 Fix documentation bugs in UG
  CommandClassDiagram.png
  docs/UserGuide.md
Labels: type.Bug, type.Documentation

#239 Made NUSMods loading + timetable saving more robust and moved saving to shutdown hook
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/data/TimeTableManager.java
  src/main/java/seedu/duke/data/storage/Decoder.java
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
  src/main/java/seedu/duke/exception/NusModsNotLoadedException.java
  src/main/java/seedu/duke/ui/TextUi.java
  src/main/java/seedu/duke/util/ExceptionMessage.java
  src/test/java/seedu/duke/command/add/AddCommandTest.java
  src/test/java/seedu/duke/command/edit/EditModuleCommandTest.java
  src/test/java/seedu/duke/command/grade/GradeCommandTest.java
  src/test/java/seedu/duke/command/misc/UndoCommandTest.java
  src/test/java/seedu/duke/command/timetable/TimeTableCommandTest.java
  src/test/java/seedu/duke/data/TimeTableTest.java
  src/test/java/seedu/duke/parser/TimeTableCommandParserTest.java
Labels: priority.High, type.Bug, type.Enhancement

#241 Amend undo command success message
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Executor.java
  src/main/java/seedu/duke/command/misc/UndoCommand.java
  src/main/java/seedu/duke/data/State.java
  src/main/java/seedu/duke/data/StateManager.java
  src/main/java/seedu/duke/util/Message.java
Labels: type.Enhancement

#240 Update UG & DG to include TimetableReset command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/TimeTableClassDiagram.png
  docs/diagrams/UML/TimeTableClassDiagram.puml
  src/main/java/seedu/duke/command/timetable/TimeTableResetCommand.java
Labels: type.Documentation

#242 Massive changes to the main class, CommandResult and TextUi
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Executor.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandResult.java
  src/main/java/seedu/duke/command/ExitCommand.java
  src/main/java/seedu/duke/command/IncorrectCommand.java
  src/main/java/seedu/duke/command/add/AddModuleCommand.java
  src/main/java/seedu/duke/command/cap/CapCommand.java
  src/main/java/seedu/duke/command/delete/DeleteModuleCommand.java
  src/main/java/seedu/duke/command/delete/DeleteTaskCommand.java
  src/main/java/seedu/duke/command/done/DoneCommand.java
  src/main/java/seedu/duke/command/edit/EditModuleCommand.java
  src/main/java/seedu/duke/command/edit/EditTaskCommand.java
  src/main/java/seedu/duke/command/grade/GradeCommand.java
  src/main/java/seedu/duke/command/misc/UndoCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableAddCommand.java
  src/main/java/seedu/duke/command/timetable/TimeTableDeleteCommand.java
  src/main/java/seedu/duke/data/Module.java
  src/main/java/seedu/duke/data/ModuleManager.java
  src/main/java/seedu/duke/data/Task.java
  src/main/java/seedu/duke/data/TaskManager.java
  src/main/java/seedu/duke/data/TimeTableManager.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/TextHelper.java
  src/main/java/seedu/duke/ui/TextUi.java
  src/main/java/seedu/duke/util/ExceptionMessage.java
  src/main/java/seedu/duke/util/Message.java
  src/test/java/seedu/duke/command/done/DoneCommandTest.java
  src/test/java/seedu/duke/command/edit/EditTaskCommandTest.java
  src/test/java/seedu/duke/command/grade/GradeCommandTest.java
Labels: priority.High, type.Enhancement

#250 Quick Fix: IOManager doesn't load NUSMods if data dir doesn't exist
  src/main/java/seedu/duke/data/storage/InputOutputManager.java
Labels: type.Bug

#249 Added PPP
  docs/UserGuide.md
  docs/team/tobiasceg.md
Labels: type.Documentation

#246 Add Sean's PPP
  docs/UserGuide.md
  docs/team/aseanseen.md
  docs/team/johndoe.md
  docs/team/template.md
Labels: type.Documentation

#252 Added tests and Amalina's pp
  docs/team/amalinasani.md
  src/main/java/seedu/ravi/command/done/DoneCommand.java
  src/main/java/seedu/ravi/command/help/HelpCommand.java
  src/main/java/seedu/ravi/command/list/ListCommand.java
  src/main/java/seedu/ravi/command/summary/SummaryCommand.java
  src/main/java/seedu/ravi/command/timetable/TimeTableResetCommand.java
  src/main/java/seedu/ravi/command/timetable/TimeTableViewCommand.java
  src/main/java/seedu/ravi/data/ModuleManager.java
  src/main/java/seedu/ravi/data/Task.java
  src/main/java/seedu/ravi/data/TaskManager.java
  src/main/java/seedu/ravi/data/TimeTableManager.java
  src/test/java/seedu/ravi/command/done/DoneCommandTest.java
  src/test/java/seedu/ravi/command/help/HelpCommandTest.java
  src/test/java/seedu/ravi/command/list/ListCommandTest.java
  src/test/java/seedu/ravi/command/summary/SummaryCommandTest.java
Labels: type.Documentation, type.Test

#251 Update DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#263 Add Jansi library
  build.gradle
  src/main/java/seedu/ravi/Ravi.java
  src/main/java/seedu/ravi/ui/TextUi.java
  src/main/java/seedu/ravi/util/Message.java
Labels: type.Enhancement

#268 Added color and some other stuff
  docs/DeveloperGuide.md
  src/main/java/seedu/ravi/RaviLogger.java
  src/main/java/seedu/ravi/command/add/AddModuleCommand.java
  src/main/java/seedu/ravi/command/add/AddTaskCommand.java
  src/main/java/seedu/ravi/command/cap/CapCommand.java
  src/main/java/seedu/ravi/command/delete/DeleteModuleCommand.java
  src/main/java/seedu/ravi/command/delete/DeleteTaskCommand.java
  src/main/java/seedu/ravi/command/done/DoneCommand.java
  src/main/java/seedu/ravi/command/edit/EditModuleCommand.java
  src/main/java/seedu/ravi/command/edit/EditTaskCommand.java
  src/main/java/seedu/ravi/command/grade/GradeCommand.java
  src/main/java/seedu/ravi/command/help/HelpCommand.java
  src/main/java/seedu/ravi/command/list/ListCommand.java
  src/main/java/seedu/ravi/command/misc/UndoCommand.java
  src/main/java/seedu/ravi/command/summary/SummaryCommand.java
  src/main/java/seedu/ravi/command/timetable/TimeTableCommand.java
  src/main/java/seedu/ravi/data/TimeTable.java
  src/main/java/seedu/ravi/data/TimeTableManager.java
  src/main/java/seedu/ravi/data/storage/InputOutputManager.java
  src/main/java/seedu/ravi/parser/AddCommandParser.java
  src/main/java/seedu/ravi/ui/TextHelper.java
  src/main/java/seedu/ravi/ui/TextUi.java
  src/main/java/seedu/ravi/util/ExceptionMessage.java
  src/main/java/seedu/ravi/util/Message.java
Labels: priority.Medium, type.Bug, type.Enhancement

#271 Quick fix for DG's Main Sequence Diagram
  docs/DeveloperGuide.md
  docs/diagrams/MainSequenceDiagram.png
Labels: priority.Low, type.Documentation

#281 Change Pages theme
  docs/_config.yml
Labels: priority.High, type.Documentation

#287 Add help bye and update help message
  src/main/java/seedu/ravi/command/ExitCommand.java
  src/main/java/seedu/ravi/command/help/HelpCommand.java
  src/main/java/seedu/ravi/util/Message.java
Labels: type.Bug

#286 Fixes timetable initialisation bug
  src/main/java/seedu/ravi/data/TimeTableManager.java
  src/main/java/seedu/ravi/ui/TextUi.java
Labels: type.Bug

#295 Revert "Merge pull request #292 from wangqinNick/master"
  docs/DeveloperGuide.md
  docs/diagrams/CommandClassDiagramGUI.png
  docs/diagrams/DataClassDiagramGUI.png
  docs/diagrams/MainClassDiagramGUI.png
  docs/diagrams/ParserClassDiagramGUI.png
  docs/diagrams/UML/seq for Undo.xml
  docs/diagrams/UndoCommandSequenceDiagram.png
  docs/team/template.md
  docs/team/wangqinNick.md
  src/main/java/seedu/ravi/data/ModuleManager.java
  src/test/java/seedu/ravi/command/misc/UndoCommandTest.java
Labels: priority.High, severity.High, type.Bug

#303 DG and PPP update
  docs/DeveloperGuide.md
  docs/diagrams/DataSequenceDiagram.png
  docs/diagrams/DataSequenceDiagramDataSd.png
  docs/diagrams/DataSequenceDiagramNusModsSd.png
  docs/diagrams/MainClassDiagram.png
  docs/diagrams/MainSequenceDiagram.png
  docs/diagrams/UML/DataSequenceDiagram.puml
  docs/diagrams/UML/DataSequenceDiagramDataSd.puml
  docs/diagrams/UML/DataSequenceDiagramNusModsSd.puml
  docs/diagrams/UML/MainClassDiagram.puml
  docs/diagrams/UML/MainSequenceDiagram.puml
  docs/diagrams/UML/MainSequenceDiagramLoopSd.puml
  docs/team/f0fz.md
  src/main/java/seedu/ravi/Executor.java
  src/main/java/seedu/ravi/Ravi.java
Labels: priority.High, type.Documentation
